version: "3"
services:
  app:
    restart: always
    build: ./
    ports:
      - "443:3000"
    volumes:
      - ./app:/app
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
